Update website after grand opening
h4ckbs/hack.bs.it pull request #3
Opened 2023-05-19 16:59 UTC by danielabrozzoni

2023-05-19 17:07 UTC, casungo approved these changes
LGTM!

2023-05-20 09:14 UTC, parsevalbtc requested changes

2023-05-20 09:14 UTC, parsevalbtc commented on content/it/_index.md
> +La nostra community è formata da circa 30 membri, tra cui sviluppatori, ingegneri, designer e studenti.
Terrei "ricercatori" ;)

2023-05-20 09:14 UTC, parsevalbtc commented on content/en/_index.md
> +Our community is currently composed of 30-ish people, including developers, engineers, designers, students, and all-rounders. We're always excited to welcome new talent - whether you're an expert or
Would keep "Researchers"

2023-05-20 09:36 UTC, parsevalbtc commented
Per il resto ACK, bel update @danielabrozzoni!

2023-05-20 10:11 UTC, merged